name: retrofit_clean
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies:
  path: ^1.8.0
  retrofit: ^2.0.1
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
  mocktail: ^0.1.4

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.2
  retrofit_generator: ^2.0.0+3
  test: ^1.17.12
